### ISSUE TITLE
poi.json ha una sintassi invalida

### ISSUE THREAD

**Issue by wbigger** [giuliacangani02/2021-marconi-turismo-Sanremo#10]
Come è possibile anche da github, il file json ha un errore di sintassi alla fine:

https://github.com/giuliacangani02/2021-marconi-turismo-Sanremo/blob/0b7f18c11d16e151f972db13382dcb8ab521c0b9/poi.json#L25-L27

Manca una parentesi quadra chiusa per chiudere la lista di POI. Per il resto sembra corretto.

**Comment by giuliacangani02** [comment]
risolto

**Comment by wbigger** [comment]
Una volta risolto, devi anche chiudere la issue, in modo che non compare più nelle cose aperte da risolvere.

**Comment by wbigger** [comment]
Credo tu non abbia fatto il push delle modifiche, qui su github non le vedo.

**Comment by giuliacangani02** [comment]
fatto ora
