### ISSUE TITLE
Linea di codice spuria

### ISSUE THREAD

**Issue by wbigger** [giuliacangani02/2021-marconi-turismo-Sanremo#11]
Alla riga 29 di data.php, c'è una riga spuria probabilmente errore di copia-incolla.

https://github.com/giuliacangani02/2021-marconi-turismo-Sanremo/blob/0b7f18c11d16e151f972db13382dcb8ab521c0b9/data.php#L27-L31

**Comment by giuliacangani02** [comment]
ok risolto questo errore

**Comment by wbigger** [comment]
Credo tu non abbia fatto il push delle modifiche, qui su github non le vedo.
