### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by giuliacangani02** [giuliacangani02/2021-marconi-turismo-Sanremo#12]
@wbigger prof puo' controllare se va meglio javascript ?

**Comment by wbigger** [comment]
@giuliacangani02 devi controllare gli errori in output che ti ritorna la console. Quando viene mostrata la pagina, clicchi con il tasto destro da qualche parte e fai ispeziona, quindi vai sulla tab "Console" e guardi gli errori che segnala. Ora dice che:
```
Uncaught SyntaxError: unexpected token: '(' script.js:7:27
```
ed in effetti ci sono delle parentesi tonde di troppo: non puoi metterle nel nome di una variabile!  Non c'è bisogno di mettere nomi così lunghi, puoi chiamare la variabile semplicemente "cattedrale". Ricordo nuovamente che le variabili devono cominciare con una lettera minuscola.

**Comment by wbigger** [comment]
Comunque per le prossime issue devi usare dei nomi più chiari, che identificano esattamente qual'è l'errore, ad esempio: "javascript non compila correttamente" o simile. All'interno della issue _devi_ specificare qual'è l'errore che ti ha restituito in console, e dettagliare anche le prove che hai fatto per risolvere l'errore. 

Come ti ho detto, all'interno del file JavaScript ci sono diversi errori. Se ogni volta cambi una riga e mi richiedi se è giusto, non ne usciremo mai. Devi andare avanti da sola il più possibile, facendo delle prove e controllando sempre la console, e poi scrivere solo nel momento in cui non riesci più ad andare avanti.

**Comment by wbigger** [comment]
Un'altra cosa: come ho detto anche a lezione, è _molto_ importante che i messaggi di commit siano significativi. Non devono essere assolutamente chiamati _push_ o con la data: sono informazioni superflue, perché non aggiungono nessuna informazione (la data è già aggiunta automaticamente a tutti i commit).

Devi mettere un commit message che sia significativo, ad esempio "corretto nome variabile in Javascript", oppure "corretta la formattazione del file json", oppure "eliminata riga spuria su PHP" o cose del genere. 

Chiudi le issue solo quando il codice committato risolve effettivamente la issue. Se credi invece che la issue per qualche motivo non debba essere risolta, scrivilo esplicitamente nel thread della issue.
