### ISSUE TITLE
Non ci compare nulla sulla console

### ISSUE THREAD

**Issue by wbigger** [giuliacangani02/2021-marconi-turismo-Sanremo#7]
Messaggio inviato da @giuliacangani02

**Comment by wbigger** [comment]
Sul readme iniziale non c'è il link al progetto replit.com, in ogni caso ho provato a scaricarlo ed eseguirlo in locale e ricevo questo errore sulla console:
```
Uncaught SyntaxError: redeclaration of let init script.js:19:4note: Previously declared at line 6, column 4 script.js:6:4
```

In effetti ci sono due dichiarazioni della funzione init, come dice il messaggio alla riga 6 ed alla riga 19. Dovete probabilmente eliminare la dichiarazione che non vi serve.

**Comment by giuliacangani02** [comment]
il mio problema è capire cosa ho sbagliato nel file script.js perchè nonostante io abbia cambiato alcune cose il problema sussiste

**Comment by giuliacangani02** [comment]
E poi gentilmente potrebbe vedere se nel file data.php e poi.json ci sono dei problemi, purtroppo non ho un riscontro con nessuno

**Comment by wbigger** [comment]
Se avvii la console ti ritorna questo errore:
```
Uncaught SyntaxError: unexpected token: identifier script.js:8:20
```
Come dice, c'è un errore nell'identificativo alla [riga 8](https://github.com/giuliacangani02/2021-marconi-turismo-Sanremo/blob/0b7f18c11d16e151f972db13382dcb8ab521c0b9/script.js#L8) di script.js. In effetti i nomi delle variabili non possono avere gli spazi.

Comunque il problema è generale: il file JavaScript è pieno di errori vari, riguardatelo anche con l'aiuto del debugger della console.
Guardate bene inoltre l'esempio di glovo: dovete fare un loop, e ad ogni loop assegnare le varie caratteristiche ad un elemento. Non dovete creare i vari elementi uno di seguito all'altro come state facendo ora.
