### ISSUE TITLE
Il container del flexbox deve essere unico

### ISSUE THREAD

**Issue by wbigger** [giuliacangani02/2021-marconi-turismo-Sanremo#9]
Con [flexbox](https://www.w3schools.com/css/css3_flexbox.asp), ci deve essere un unico container che contiene tutti gli "item" che devono essere mostrati nella griglia. 

Fare anche riferimento come al solito al [progetto Glovo-PHP](https://replit.com/@ccapobianco/Glovo-PHP#index.php) su replit per avere un esempio.

Questa riga deve essere unica nell'index.html:
https://github.com/giuliacangani02/2021-marconi-turismo-Sanremo/blob/0b7f18c11d16e151f972db13382dcb8ab521c0b9/index.html#L15

**Comment by giuliacangani02** [comment]
non riesco a capire

**Comment by wbigger** [comment]
Come dice la parola, container è il contenitore del flexbox, quindi è l'elemento che deve stare subito sopra gli elementi da ordinare.

Qualcosa del genere:
```html
 <div class="container">
  <div>Poi 1</div>
  <div>Poi 2</div>
  <div>Poi 3</div>
</div> 
```

**Comment by giuliacangani02** [comment]
<div class="container"> 
    <div class="image">
      <img src="Concattedrale.jpg" alt="Concattedrale.jpg">
    </div>
    <div class="location">
      <p class="monument">Concattedrale di Sanremo (5 km)</p>
      <p class="disp">Posti disponibili : 34</p>
      <p class="description">"La concattedrale di San Siro (nome completo: Insigne Basilica Collegiata Concattedrale di San Siro) è l'edificio religioso più antico di Sanremo e uno dei principali esempi di architettura romanica nel ponente ligure. Situata nel centro storico, nell'omonima piazza, è stata eretta nel XII secolo."</p>
    </div>

perche' cosi non e sopra??

**Comment by giuliacangani02** [comment]
perche' cosi non e' sopra?
<div class="container"> 
   <div class="image">
     <img src="Concattedrale.jpg" alt="Concattedrale.jpg">
    </div>
    <div class="location">
      <p class="monument">Concattedrale di Sanremo (5 km)</p>
      <p class="disp">Posti disponibili : 34</p>
      <p class="description">"La concattedrale di San Siro (nome completo: Insigne Basilica Collegiata Concattedrale di San Siro) è l'edificio religioso più antico di Sanremo e uno dei principali esempi di architettura romanica nel ponente ligure. Situata nel centro storico, nell'omonima piazza, è stata eretta nel XII secolo."</p>
    </div>

**Comment by giuliacangani02** [comment]
<div class="container"> 
    <div class="image">
      <img src="Concattedrale.jpg" alt="Concattedrale.jpg">
    </div>
    <div class="location">
      <p class="monument">Concattedrale di Sanremo (5 km)</p>
      <p class="disp">Posti disponibili : 34</p>
      <p class="description">"La concattedrale di San Siro (nome completo: Insigne Basilica Collegiata Concattedrale di San Siro) è l'edificio religioso più antico di Sanremo e uno dei principali esempi di architettura romanica nel ponente ligure. Situata nel centro storico, nell'omonima piazza, è stata eretta nel XII secolo."</p>
    </div>

**Comment by wbigger** [comment]
Hai chiuso la issue ma vedo ancora diversi container nell'index.html...
